#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=happynet  Configuration module
LUCI_DEPENDS:=+n2n-happyn
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-happynet

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
